- name: Configure cos-web1 (Ubuntu 24.04)
  hosts: cos-web1
  become: true
  tasks:

  - name: Install a list of packages
    apt:
       pkg:
       - vim
       - git
       - nano
       - net-tools
       - tcsh
       - zsh
       - gawk
       - rdate
       - screen
       - tmux
       - curl
       - whois
       - cifs-utils
       - apache2
       - php
       - webalizer
       - software-properties-common
       - apt-transport-https
       - build-essential
       - snap
       - dirmngr
       - gdebi-core
       - autofs
       - gparted
       state: present
       update_cache: yes

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

