- name: Configure st-web6 (Ubuntu 22.04)
  hosts: st-web6
  become: true
  tasks:

  - name: Install a list of packages
    apt:
       pkg:
       - vim
       - git
       - nano
       - net-tools
       - tcsh
       - zsh
       - gawk
       - rdate
       - screen
       - tmux
       - curl
       - whois
       - cifs-utils
       - apache2
       - php
       - webalizer
       - software-properties-common
       - apt-transport-https
       - build-essential
       - snap
       - dirmngr
       - gdebi-core
       - lib32gcc-s1
       - lib32stdc++6
       - libc6-i386
       - libclang-dev
       - libgc1
       - libobjc4
       - libpq5
       - libssl-dev
       - rrdtool
       - texlive-full
       - libxml2-dev
       - libfontconfig1-dev
       - libcurl4-openssl-dev
       - libharfbuzz-dev
       - libfribidi-dev
       - libfreetype6-dev
       - libpng-dev
       - libtiff5-dev
       - libjpeg-dev
       - libsqlite3-dev
       - libssl-dev
       - libsasl2-dev
       - gnupg
       - autofs
       - gparted
       - media-types
       - jq
       - libsodium-dev
       - gdal-bin
       - libgdal-dev
       - libudunits2-dev
       - cmake
       - libssl-dev
       - libsasl2-dev
       - libudunits2-dev
       - libmagick++-dev
       - cargo
       - libjq-dev
       - libgsl-dev
       state: present
       update_cache: yes

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

